title = "Hugo: A Fast and Flexible Website Generator"
baseurl = "http://hugo.yushuangqi.com/"
MetaDataFormat = "yaml"
pluralizeListTitles = false 
uglyURLs = true
languageCode = "zh"

[params]
  description = "由Golang爱好者虞双齐维护的 Hugo中文版文档。Hugo是spf13和他得朋友使用 Go 开发的一个极速灵活的静态网站创建工具。"
  author = "虞双齐"
  lang= "zh"
  #指定大部分静态文件地址，主要用于 DNS 加速
  staticURL = "http://static.hugo.yushuangqi.com"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "下载Hugo"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = -200
[[menu.main]]
    name = "网站案例"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/showcase/"
    weight = -180
[[menu.main]]
    name = "主题浏览"
    pre = "<i class='fa fa-puzzle-piece'></i>"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "动态"
    pre = "<i class='fa fa-bullhorn'></i>"
    url = "/community/press/"
    weight = -160
[[menu.main]]
    name = "论坛"
    pre = "<i class='fa fa-comments'></i>"
    url = "http://discuss.gohugo.io/"
    weight = -150
[[menu.main]]
    name = "关于Hugo"
    identifier = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "入门指引"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "写作"
    identifier = "content"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -90
[[menu.main]]
    name = "主题"
    identifier = "themes"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85
[[menu.main]]
    parent = "themes"
    name = "主题浏览"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "模板"
    identifier = "layout"
    pre = "<i class='fa fa-columns'></i>"
    weight = -80
[[menu.main]]
    name = "分类标签"
    identifier = "taxonomy"
    pre = "<i class='fa fa-tags'></i>"
    weight = -70
[[menu.main]]
    name = "附近功能"
    identifier = "extras"
    pre = "<i class='fa fa-gift'></i>"
    weight = -60
[[menu.main]]
    name = "社区"
    identifier = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -50
[[menu.main]]
    parent = "community"
    name = "Discussion Forum"
    url = "http://discuss.gohugo.io"
    weight = 150
[[menu.main]]
    name = "使用手册"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "常见问题"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
[[menu.main]]
    name = "工具"
    url = "/tools/"
    pre = "<i class='fa fa-cogs'></i>"
    weight = -25
[[menu.main]]
    name = "Hugo命令参考"
    identifier = "commands"
    pre = "<i class='fa fa-space-shuttle'></i>"
    weight = -20
    url = "/commands/"