title = "Hugo: A Fast and Flexible Website Generator"
baseurl = "http://hugo.yushuangqi.com/"
MetaDataFormat = "yaml"
pluralizeListTitles = false 
uglyURLs = true
languageCode = "zh-CN"

[params]
  description = "由Golang爱好者虞双齐维护的 Hugo中文版文档。Hugo是spf13和他得朋友使用 Go 开发的一个极速灵活的静态网站创建工具。"
  author = "虞双齐"
  lang= "zh-CN"
  #指定大部分静态文件地址，主要用于 DNS 加速
  staticURL = "http://static.hugo.yushuangqi.com"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Download Hugo"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = -200
[[menu.main]]
    name = "Site Showcase"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/showcase/"
    weight = -180
[[menu.main]]
    name = "Theme Showcase"
    pre = "<i class='fa fa-puzzle-piece'></i>"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "Press & Articles"
    pre = "<i class='fa fa-bullhorn'></i>"
    url = "/community/press/"
    weight = -160
[[menu.main]]
    name = "Discuss Hugo"
    pre = "<i class='fa fa-comments'></i>"
    url = "http://discuss.gohugo.io/"
    weight = -150
[[menu.main]]
    name = "About Hugo"
    identifier = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "入门"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "Content"
    identifier = "content"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -90
[[menu.main]]
    name = "Themes"
    identifier = "themes"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85
[[menu.main]]
    parent = "themes"
    name = "Theme Showcase"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "Templates"
    identifier = "layout"
    pre = "<i class='fa fa-columns'></i>"
    weight = -80
[[menu.main]]
    name = "Taxonomies"
    identifier = "taxonomy"
    pre = "<i class='fa fa-tags'></i>"
    weight = -70
[[menu.main]]
    name = "Extras"
    identifier = "extras"
    pre = "<i class='fa fa-gift'></i>"
    weight = -60
[[menu.main]]
    name = "Community"
    identifier = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -50
[[menu.main]]
    parent = "community"
    name = "Discussion Forum"
    url = "http://discuss.gohugo.io"
    weight = 150
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
[[menu.main]]
    name = "Tools"
    url = "/tools/"
    pre = "<i class='fa fa-cogs'></i>"
    weight = -25
[[menu.main]]
    name = "Hugo Cmd Reference"
    identifier = "commands"
    pre = "<i class='fa fa-space-shuttle'></i>"
    weight = -20
    url = "/commands/"
[[menu.main_zh]]
    name = "入门"
    identifier = "getting started2"
    pre = "<i class='fa fa-road'></i>"
    weight = -100